steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/contract-fetcher', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/contract-fetcher']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'contract-fetcher', '--image', 'gcr.io/$PROJECT_ID/contract-fetcher', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['scheduler', 'jobs', 'create', 'http', 'fetch-contracts-job', '--schedule', '0 6 * * *', '--uri', 'https://YOUR_CLOUD_RUN_URL', '--http-method', 'POST']